project:
  type: book

book:
  title: "Libro"
  author: "Luis Jaramillo"
  date: "8/11/2024"
  chapters:

    
    - index.qmd
    - part: "Unidad 1: Nombre de la Unidad"
      chapters: 
        - Unidades/unidad1/intro.qmd     
    - part: "Unidad 2: Entorno de Desarrollo"
      chapters: 
        - Unidades/unidad2/cap2.qmd

    - part: "Unidad 3: Paradigmas de Programación"
      chapters: 
        - Unidades/unidad3/cap3.qmd
      
    - part: "Unidad 4: Conceptos Generales de la POO"
      chapters: 
        - Unidades/unidad4/cap4.qmd
    
    - part: "Unidad 5: Modelamiento de clases y objetos"
      chapters: 
        - Unidades/unidad5/cap5.qmd

    - part: "Unidad 6: Codigo Limpio"
      chapters: 
        - Unidades/unidad6/cap6.qmd

    - part: "Unidad 7: Estructura General de un Programa"
      chapters: 
        - Unidades/unidad7/cap7.qmd

    - part: "Unidad 8: Lectura y Escritura de Datos por consola"
      chapters: 
        - Unidades/unidad8/cap8.qmd
    
    - part: "Unidad 9: Manejor de Exepciones"
      chapters: 
        - Unidades/unidad9/cap9.qmd
        
    - part: "Unidad 10: Array - Arreglos"
      chapters: 
        - Unidades/unidad10/cap10.qmd

    - part: "Unidad 11: Encapsulamiento"
      chapters: 
        - Unidades/unidad11/cap11.qmd

    - part: "Unidad 12: Constructores"
      chapters: 
        - Unidades/unidad12/cap12.qmd
    
    - part: "Unidad 13: Getter & Setter"
      chapters: 
        - Unidades/unidad13/cap13.qmd
    
    - part: "Unidad 14: Persistencia de datos"
      chapters: 
        - Unidades/unidad14/cap14.qmd

    - part: "Ejercicio1"
      chapters: 
        - Unidades/Ejercicio1/ejercicio.qmd



    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



