---
title: "R apuntes"
author: "Luis Jaramillo"
format: 
  html: default
  pdf: default
editor: visual
---

## Programación Orientada a Objetos.

La programación orientada a objetos (POO) es un paradigma de programación que se basa en el concepto de "objetos", los cuales son instancias de clases. En POO, un "objeto" puede entenderse como una entidad que encapsula datos y funciones que operan sobre esos datos. Este enfoque permite modelar el mundo real de manera más efectiva, ya que se pueden representar entidades y sus interacciones de manera más natural.

En POO, una "clase" es un plano o plantilla para crear objetos. Define la estructura y el comportamiento de los objetos que se crearán a partir de ella. Los objetos son instancias concretas de una clase, y cada objeto puede tener sus propios datos (llamados atributos) y funciones (llamadas métodos).

Los cuatro principios fundamentales de la POO son la encapsulación, la herencia, el polimorfismo y la abstracción. La "**encapsulación**" implica la ocultación de los detalles internos de un objeto y la exposición solo de lo necesario. La "**herencia**" permite la creación de nuevas clases basadas en clases existentes, heredando sus atributos y métodos. El "**polimorfismo**" permite que un objeto pueda tomar varias formas, es decir, un mismo método puede comportarse de manera diferente según el contexto. La "**abstracción**" consiste en simplificar la representación de un objeto centrándose en los aspectos esenciales y omitiendo los detalles innecesarios.

Para el siguiente documento revisaremos las siguientes temáticas:

## [Entorno de Desarrollo](Entorno_de_Desarrollo.html)

## [control de versionamiento](control%20de%20versionamiento.html)

## [Paradigmas de programación.html](Paradigmas%20de%20programación.html)

## [Conceptos Generales de la POO.html](Conceptos%20Generales%20de%20la%20POO.html)

## [Modelamiento de clases y objetos](UML.html)

## [Estructura General de un Programa](estructura_general_programa.html)

## [Código limpio.html](Código%20limpio.html)

## \[Estructura General de un Programa.html\]

## \[Lectura y Escritura de datos por consola.html\]

\[#TIPOS DE DATOS.\]

## [2.html](2.html)

En este resumen se indica que podemos hacer con R studio desde lo básico hasta lo visto en las clases.
